models:
  - type: main
    engine: openai
    model: qwen/qwen3.8-27b
    api_key_env_var: GROQ_API_KEY
    parameters:
      base_url: "https://api.groq.com/openai/v1"

  - type: embeddings
    engine: SentenceTransformers
    model: NeuML/bioclinical-modernbert-base-embeddings